#!/usr/local/bin/bash

ssh-add -D

SERVER="hildeguard.scireum.com"
REMOTE_USER="${USER}"

KEY_DIRECTORY="${HOME}/.ssh"

PUBLIC_KEYS=$(ls -1 ${KEY_DIRECTORY}/*.pub 2>/dev/null | grep -v "cert")

if [ -z "${PUBLIC_KEYS}" ]; then
  echo "no ssh keys found in ${KEY_DIRECTORY}"
  exit 1
fi

for KEY in $PUBLIC_KEYS; do
  PRIVATE_KEY=$(echo $KEY | sed 's/.pub//')
  CERT_KEY_NAME="${PRIVATE_KEY}-cert.pub"
  KEY_BASENAME=$(basename $PRIVATE_KEY)

  echo "sending ${KEY_BASENAME} to HildeGuard..."
  ssh ${REMOTE_USER}@${SERVER} sign < $KEY > ${CERT_KEY_NAME}

  ssh-add $PRIVATE_KEY
done
