#!/bin/bash

SSH_CONFIG_URL="http://scireum-vmc1-prod-puppet-1.scireum.com/ssh_config"
SSH_KNOWN_HOSTS_URL="http://scireum-vmc1-prod-puppet-1.scireum.com/known_hosts.puppet"

# Installation
# sudo curl -s -o /usr/local/bin/update-ssh-config http://scireum-prod-puppet-1.scireum.com/update-ssh-config && sudo chmod +x /usr/local/bin/update-ssh-config

if [ -z $HOME ]; then
	echo "HOME variable not set"
	exit 1
fi

SSH_DIRECTORY="${HOME}/.ssh"

SSH_CONFIG="${SSH_DIRECTORY}/config"
SSH_FOOTER="${SSH_DIRECTORY}/config.footer"
SSH_KNOWN_HOSTS="${SSH_DIRECTORY}/known_hosts.puppet"

if [ ! -f $SSH_FOOTER ] && [ -f $SSH_CONFIG ]; then
	echo ""
	echo "File ${SSH_FOOTER} not found!"
	echo ""
	echo "If you are a first time user. Please run:"
	echo "   cp ${SSH_CONFIG} ${SSH_FOOTER}"
	echo ""
	exit 1
fi

TEMP_CONFIG=$(mktemp -t ssh_config)
curl -s --output $TEMP_CONFIG ${SSH_CONFIG_URL}

curl -s --output $SSH_KNOWN_HOSTS ${SSH_KNOWN_HOSTS_URL}

if [ -f ${SSH_CONFIG} ]; then
	cp ${SSH_CONFIG} ${SSH_CONFIG}.backup
fi
cat $TEMP_CONFIG $SSH_FOOTER > $SSH_CONFIG

rm $TEMP_CONFIG
